---
functional:
  - На главной странице можно создать битву без регистрации
  - Пользователь может авторизоваться
  - После авторизации отображается сообщение об успешной аутентификации пользователя
  - Пользователь может просматривать свои турниры 
  - Пользователь может присоединиться к турниру, который начал другой пользователь из вкладки LOBBY 
  - Пользователь может создать игру 
  - Пользователь может установить сложность созданной игры
  - Пользователь может создать игру с другими пользователями
  - Пользователь может создать игру с другом
  - Пользователь может выбрать тип задачи включая случайное задание
  - Во время турнира игрок может выбрать язык отображения задания из предложенных
  - Во время турнира игрок может выбрать язык программирования, на котором будет выполнять задание 
  - Время турнира отображается корректно 
non-functional:
  - Игра должна быть разработана с учетом удобства использования и оптимизирована для скорости работы
  - Игра должна быть безопасной и защищать данные пользователя
  - Игра является кроссбраузерной 
  - Игра является адаптивной 
  - Игра должна быть способна обрабатывать большое количество трафика из 1000 одновременных пользователей
implicit:
  - На главной странице неавторизованного пользователя имеется описание проекта
  - На главной странице есть кнопка для регистрации нового пользователя
  - На главной странице есть кнопка для входа пользователя 
  - Пользователь во время турнира может сдаться, сбросить решение в редакторе или проверить его
  - Из игры можно перейти на домашнюю страницу LOBBY без завершения турнира и вернуться обратно в игру, пока не истекло время, выделенное на турнир
  - Отображается форма для подтверждения, что пользователь действительно хочет сдаться 
  - Отображается сообщение о том, что турнир проигран
  - Отображается сообщение о том, что турнир выигран
  - Нажимая на логотип игры в шапке происходит переход на начальную страницу LOBBY